SELECT * FROM Insa5_JSB_hacksim_4.poke_info;

select poke_img from poke_info where poke_num = 1;

INSERT INTO poke_info (poke_num, poke_name, poke_type, poke_img, poke_b_img, poke_evol)
VALUES 
(1, '이상해씨', '["grass", "poison"]', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/1.gif', NULL, NULL),
(2, '이상해풀', '["grass", "poison"]', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/2.gif', NULL, NULL),
(3, '이상해꽃', '["grass", "poison"]', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/3.gif', NULL, NULL),
(4, '파이리', '["fire"]', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/4.gif', NULL, NULL),
(5, '리자드', '["fire"]', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/5.gif', NULL, NULL),
(6, '리자몽', '["fire", "flying"]', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/6.gif', NULL, NULL),
(7, '꼬부기', '["water"]', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/7.gif', NULL, NULL),
(8, '어니부기', '["water"]', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/8.gif', NULL, NULL),
(9, '거북왕', '["water"]', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/9.gif', NULL, NULL),
(10, '캐터피', '["bug"]', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/10.gif', NULL, NULL),
(11, '단데기', '["bug"]', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/11.gif', NULL, NULL),
(12, '버터플', '["bug", "flying"]', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/12.gif', NULL, NULL),
(13, '뿔충이', '["bug", "poison"]', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/13.gif', NULL, NULL),
(14, '딱충이', '["bug", "poison"]', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/14.gif', NULL, NULL),
(15, '독침붕', '["bug", "poison"]', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/15.gif', NULL, NULL),
(16, '구구', '["normal", "flying"]', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/16.gif', NULL, NULL),
(17, '피죤', '["normal", "flying"]', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/17.gif', NULL, NULL),
(18, '피죤투', '["normal", "flying"]', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/18.gif', NULL, NULL),
(19, '꼬렛', '["normal"]', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/19.gif', NULL, NULL),
(20, '레트라', '["normal"]', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/20.gif', NULL, NULL),
(21, '깨비참', '["normal", "flying"]', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/21.gif', NULL, NULL),
(22, '깨비드릴조', '["normal", "flying"]', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/22.gif', NULL, NULL),
(23, '아보', '["poison"]', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/23.gif', NULL, NULL),
(24, '아보크', '["poison"]', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/24.gif', NULL, NULL),
(25, '피카츄', '["electric"]', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/25.gif', NULL, NULL),
(26, '라이츄', '["electric"]', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/26.gif', NULL, NULL),
(27, '모래두지', '["ground"]', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/27.gif', NULL, NULL),
(28, '고지', '["ground"]', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/28.gif', NULL, NULL),
(29, '니드런♀', '["poison"]', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/29.gif', NULL, NULL),
(30, '니드리나', '["poison"]', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/30.gif', NULL, NULL),
(31, '니드퀸', '["poison", "ground"]', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/31.gif', NULL, NULL),
(32, '니드런♂', '["poison"]', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/32.gif', NULL, NULL),
(33, '니드리노', '["poison"]', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/33.gif', NULL, NULL),
(34, '니드킹', '["poison", "ground"]', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/34.gif', NULL, NULL),
(35, '삐삐', '["fairy"]', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/35.gif', NULL, NULL),
(36, '픽시', '["fairy"]', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/36.gif', NULL, NULL),
(37, '식스테일', '["fire"]', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/37.gif', NULL, NULL),
(38, '나인테일', '["fire"]', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/38.gif', NULL, NULL),
(39, '푸린', '["normal", "fairy"]', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/39.gif', NULL, NULL),
(40, '푸크린', '["normal", "fairy"]', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/40.gif', NULL, NULL),
(41, '주뱃', '["poison", "flying"]', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/41.gif', NULL, NULL),
(42, '골뱃', '["poison", "flying"]', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/42.gif', NULL, NULL),
(43, '뚜벅쵸', '["grass", "poison"]', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/43.gif', NULL, NULL),
(44, '냄새꼬', '["grass", "poison"]', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/44.gif', NULL, NULL),
(45, '라플레시아', '["grass", "poison"]', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/45.gif', NULL, NULL),
(46, '파라스', '["bug", "grass"]', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/46.gif', NULL, NULL),
(47, '파라섹트', '["bug", "grass"]', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/47.gif', NULL, NULL),
(48, '콘팡', '["bug", "poison"]', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/48.gif', NULL, NULL),
(49, '도나리', '["bug", "poison"]', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/49.gif', NULL, NULL),
(50, '디그다', '["ground"]', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/50.gif', NULL, NULL),
(51, '닥트리오', '["ground"]', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/51.gif', NULL, NULL),
(52, '나옹', '["normal"]', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/52.gif', NULL, NULL),
(53, '페르시온', '["normal"]', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/53.gif', NULL, NULL),
(54, '고라파덕', '["water"]', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/54.gif', NULL, NULL),
(55, '골덕', '["water"]', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/55.gif', NULL, NULL),
(56, '망키', '["fighting"]', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/56.gif', NULL, NULL),
(57, '성원숭', '["fighting"]', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/57.gif', NULL, NULL),
(58, '가디', '["fire"]', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/58.gif', NULL, NULL),
(59, '윈디', '["fire"]', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/59.gif', NULL, NULL),
(60, '발챙이', '["water"]', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/60.gif', NULL, NULL),
(61, '슈륙챙이', '["water"]', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/61.gif', NULL, NULL),
(62, '강챙이', '["water", "fighting"]', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/62.gif', NULL, NULL),
(63, '캐이시', '["psychic"]', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/63.gif', NULL, NULL),
(64, '윤겔라', '["psychic"]', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/64.gif', NULL, NULL),
(65, '후딘', '["psychic"]', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/65.gif', NULL, NULL),
(66, '알통몬', '["fighting"]', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/66.gif', NULL, NULL),
(67, '근육몬', '["fighting"]', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/67.gif', NULL, NULL),
(68, '괴력몬', '["fighting"]', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/68.gif', NULL, NULL),
(69, '모다피', '["grass", "poison"]', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/69.gif', NULL, NULL),
(70, '우츠동', '["grass", "poison"]', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/70.gif', NULL, NULL),
(71, '우츠보트', '["grass", "poison"]', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/71.gif', NULL, NULL),
(72, '왕눈해', '["water", "poison"]', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/72.gif', NULL, NULL),
(73, '독파리', '["water", "poison"]', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/73.gif', NULL, NULL),
(74, '꼬마돌', '["rock", "ground"]', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/74.gif', NULL, NULL),
(75, '데구리', '["rock", "ground"]', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/75.gif', NULL, NULL),
(76, '딱구리', '["rock", "ground"]', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/76.gif', NULL, NULL),
(77, '포니타', '["fire"]', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/77.gif', NULL, NULL),
(78, '날쌩마', '["fire"]', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/78.gif', NULL, NULL),
(79, '야돈', '["water", "psychic"]', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/79.gif', NULL, NULL),
(80, '야도란', '["water", "psychic"]', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/80.gif', NULL, NULL),
(81, '코일', '["electric", "steel"]', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/81.gif', NULL, NULL),
(82, '레어코일', '["electric", "steel"]', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/82.gif', NULL, NULL),
(83, '파오리', '["normal", "flying"]', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/83.gif', NULL, NULL),
(84, '두두', '["normal", "flying"]', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/84.gif', NULL, NULL),
(85, '두트리오', '["normal", "flying"]', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/85.gif', NULL, NULL),
(86, '쥬쥬', '["water"]', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/86.gif', NULL, NULL),
(87, '쥬레곤', '["water", "ice"]', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/87.gif', NULL, NULL),
(88, '질퍽이', '["poison"]', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/88.gif', NULL, NULL),
(89, '질뻐기', '["poison"]', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/89.gif', NULL, NULL),
(90, '셀러', '["water"]', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/90.gif', NULL, NULL),
(91, '파르셀', '["water", "ice"]', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/91.gif', NULL, NULL),
(92, '고오스', '["ghost", "poison"]', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/92.gif', NULL, NULL),
(93, '고우스트', '["ghost", "poison"]', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/93.gif', NULL, NULL),
(94, '팬텀', '["ghost", "poison"]', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/94.gif', NULL, NULL),
(95, '롱스톤', '["rock", "ground"]', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/95.gif', NULL, NULL),
(96, '슬리프', '["psychic"]', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/96.gif', NULL, NULL),
(97, '슬리퍼', '["psychic"]', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/97.gif', NULL, NULL),
(98, '크랩', '["water"]', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/98.gif', NULL, NULL),
(99, '킹크랩', '["water"]', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/99.gif', NULL, NULL),
(100, '찌리리공', '["electric"]', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/100.gif', NULL, NULL),
(101, '붐볼', '["electric"]', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/101.gif', NULL, NULL),
(102, '아라리', '["grass", "psychic"]', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/102.gif', NULL, NULL),
(103, '나시', '["grass", "psychic"]', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/103.gif', NULL, NULL),
(104, '탕구리', '["ground"]', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/104.gif', NULL, NULL),
(105, '텅구리', '["ground"]', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/105.gif', NULL, NULL),
(106, '시라소몬', '["fighting"]', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/106.gif', NULL, NULL),
(107, '홍수몬', '["fighting"]', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/107.gif', NULL, NULL),
(108, '내루미', '["normal"]', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/108.gif', NULL, NULL),
(109, '또가스', '["poison"]', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/109.gif', NULL, NULL),
(110, '또도가스', '["poison"]', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/110.gif', NULL, NULL),
(111, '뿔카노', '["ground", "rock"]', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/111.gif', NULL, NULL),
(112, '코뿌리', '["ground", "rock"]', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/112.gif', NULL, NULL),
(113, '럭키', '["normal"]', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/113.gif', NULL, NULL),
(114, '덩쿠리', '["grass"]', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/114.gif', NULL, NULL),
(115, '캥카', '["normal"]', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/115.gif', NULL, NULL),
(116, '쏘드라', '["water"]', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/116.gif', NULL, NULL),
(117, '시드라', '["water"]', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/117.gif', NULL, NULL),
(118, '콘치', '["water"]', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/118.gif', NULL, NULL),
(119, '왕콘치', '["water"]', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/119.gif', NULL, NULL),
(120, '별가사리', '["water"]', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/120.gif', NULL, NULL),
(121, '아쿠스타', '["water", "psychic"]', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/121.gif', NULL, NULL),
(122, '마임맨', '["psychic", "fairy"]', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/122.gif', NULL, NULL),
(123, '스라크', '["bug", "flying"]', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/123.gif', NULL, NULL),
(124, '루주라', '["ice", "psychic"]', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/124.gif', NULL, NULL),
(125, '에레브', '["electric"]', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/125.gif', NULL, NULL),
(126, '마그마', '["fire"]', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/126.gif', NULL, NULL),
(127, '쁘사이저', '["bug"]', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/127.gif', NULL, NULL),
(128, '켄타로스', '["normal"]', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/128.gif', NULL, NULL),
(129, '잉어킹', '["water"]', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/129.gif', NULL, NULL),
(130, '갸라도스', '["water", "flying"]', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/130.gif', NULL, NULL),
(131, '라프라스', '["water", "ice"]', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/131.gif', NULL, NULL),
(132, '메타몽', '["normal"]', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/132.gif', NULL, NULL),
(133, '이브이', '["normal"]', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/133.gif', NULL, NULL),
(134, '샤미드', '["water"]', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/134.gif', NULL, NULL),
(135, '쥬피썬더', '["electric"]', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/135.gif', NULL, NULL),
(136, '부스터', '["fire"]', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/136.gif', NULL, NULL),
(137, '폴리곤', '["normal"]', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/137.gif', NULL, NULL),
(138, '암나이트', '["rock", "water"]', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/138.gif', NULL, NULL),
(139, '암스타', '["rock", "water"]', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/139.gif', NULL, NULL),
(140, '투구', '["rock", "water"]', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/140.gif', NULL, NULL),
(141, '투구푸스', '["rock", "water"]', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/141.gif', NULL, NULL),
(142, '프테라', '["rock", "flying"]', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/142.gif', NULL, NULL),
(143, '잠만보', '["normal"]', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/143.gif', NULL, NULL),
(144, '프리져', '["ice", "flying"]', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/144.gif', NULL, NULL),
(145, '썬더', '["electric", "flying"]', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/145.gif', NULL, NULL),
(146, '파이어', '["fire", "flying"]', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/146.gif', NULL, NULL),
(147, '미뇽', '["dragon"]', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/147.gif', NULL, NULL),
(148, '신뇽', '["dragon"]', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/148.gif', NULL, NULL),
(149, '망나뇽', '["dragon", "flying"]', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/149.gif', NULL, NULL),
(150, '뮤츠', '["psychic"]', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/150.gif', NULL, NULL);
